on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: Build and tag the docker image
        run: |
          docker build -t yt-upload-service:$NOW .
          docker tag yt-upload-service:$NOW ytbackend.azurecr.io/yt-upload-service:$NOW

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Push the docker image
        run : |
          az acr login --name ytbackend
          docker push ytbackend.azurecr.io/yt-upload-service:$NOW

      - name : Instruct Azure Container App to pull this image
        run : |
          az containerapp update \
            --name yt-upload-service-container-app \
            --resource-group crushed-lemon-yt \
            --image ytbackend.azurecr.io/yt-upload-service:$NOW
